build:
  tools:
    python: "3.8"
  commands:
    - pip install pytorch
    - export TORCH=`python -c "import torch; print(torch.__version__)"`
    - pip install torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}+cpu.html
    - pip install torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}+cpu.html
    - pip install torch-geometric
  
python:
  version: "3.8"
  install:
    - requirements: docs/requirements.txt
